# Generated by Django 5.1.4 on 2025-01-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='letter_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(choices=[('Gujarat Refinery', 'Gujarat Refinery')], max_length=30)),
                ('returnable', models.CharField(choices=[('Returnable', 'Returnable'), ('Non-Returnable', 'Non-Returnable')], max_length=20)),
                ('destination', models.CharField(max_length=50)),
            ],
        ),
    ]
