# Generated by Django 5.1.4 on 2025-01-02 05:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter_information',
            name='letter_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
