# Generated by Django 5.1.4 on 2025-01-02 05:37

import uuid
from django.db import migrations

def gen_uuid(apps, schema_editor):
    letter_information = apps.get_model("Invoice","letter_information")
    for row in letter_information.objects.all():
        row.letter_id = uuid.uuid4()
        row.save(update_fields=['letter_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0002_letter_information_letter_id'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
