# Generated by Django 5.1.4 on 2025-01-02 07:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0004_auto_20250102_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter_information',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='list_of_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invoice.letter_information')),
            ],
        ),
    ]
