# Generated by Django 5.1.4 on 2025-01-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0005_letter_information_date_list_of_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list_of_items',
            options={'verbose_name_plural': 'list_of_items'},
        ),
        migrations.AlterField(
            model_name='list_of_items',
            name='table_id',
            field=models.CharField(max_length=150),
        ),
    ]
