# Generated by Django 5.1.4 on 2025-01-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0006_alter_list_of_items_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter_information',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
