# Generated by Django 5.1.4 on 2025-01-02 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0007_alter_letter_information_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter_information',
            name='source',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='letter_information',
            name='destination',
            field=models.CharField(max_length=100),
        ),
    ]
