# Generated by Django 5.1.4 on 2025-01-03 10:27

import Invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0008_letter_information_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter_information',
            name='date',
            field=models.DateTimeField(default=Invoice.models.get_current_time_utc530),
        ),
    ]
