# Generated by Django 5.1.4 on 2025-01-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0010_letter_information_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter_information',
            name='name',
            field=models.CharField(choices=[('Kesaba Trilochan Panda', 'Kesaba Trilochan Panda')], max_length=50),
        ),
    ]
